project_id = "ifesxveahsbjhmrhkhhy"

[functions.generate]
verify_jwt = false

[functions.check-generation]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-models]
verify_jwt = false

[functions.image-tools]
verify_jwt = false

[functions.video-tools]
verify_jwt = false
