project_id = "hpuqeabtgwbwcnklxolt"

[functions.ai-video-edit]
verify_jwt = false

[functions.generate]
verify_jwt = false

[functions.mobile-subscription]
verify_jwt = false

[functions.skin-ai]
verify_jwt = false

[functions.financial-ai]
verify_jwt = false

[functions.fingerprint-ai]
verify_jwt = false

[functions.calorie-ai]
verify_jwt = false

[functions.notify-ai]
verify_jwt = false

[functions.notify-ai-save]
verify_jwt = false

[functions.brain-ai]
verify_jwt = false

[functions.sleep-ai]
verify_jwt = false

[functions.music-generation]
verify_jwt = false

[functions.music-tools]
verify_jwt = false

[functions.video-tools]
verify_jwt = false

[functions.gemini-live-token]
verify_jwt = false
